FROM gradle:8.10.2-jdk21

RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
EXPOSE 8080

CMD ["gradle", "bootRun", "--no-daemon"]
